spring:
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        #default_batch_fetch_size: 1000
        jdbc:
          lob:
            non_contextual_creation: true
logging.level:
  org.hibernate.type.descriptor.sql: debug